import Head from 'next/head'
import UnderConstruction from "../component/underConstruction";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Audiowide&display=swap" rel="stylesheet"/>
      </Head>
        <UnderConstruction background={'/background.jpg'}>
                Coming Soon
            <UnderConstruction.Mail>
                s.kozlowski@globalaccounting.pl
            </UnderConstruction.Mail>
        </UnderConstruction>
    </div>
  )
}
